### ISSUE TITLE
Add appropriate comments to tha code 

### ISSUE THREAD

**Issue by LalitDhane** [LalitDhane/blog#3]

**Comment by hassana123** [comment]
Would like to work on this @LalitDhane

**Comment by LalitDhane** [comment]
Good to see you are interested in contributing!

I've assigned you for this issue

**Comment by Jangyaseni666** [comment]
I would like to help add appropriate comments(assuming the issue is not fixed as it is still open). Can you please assign this to me?

**Comment by LalitDhane** [comment]
Sure

**Comment by Jangyaseni666** [comment]
> Sure
> 

Thanku!
